export const ProviderType = {
  1: { text: 'LP', value: 1 },
  2: { text: 'LMFT', value: 2 },
  3: { text: 'AMFT', value: 3 },
  4: { text: 'LCSW', value: 4 },
  5: { text: 'ACSW', value: 5 },
  6: { text: 'LPCC', value: 6 },
  7: { text: 'APCC', value: 7 },
  8: { text: 'LEP', value: 8 },
  9: { text: 'EP', value: 9 },
  10: { text: 'NP', value: 10 },
  11: { text: 'Psychiatrist', value: 11 },
  12: { text: 'MD', value: 12 },
  13: { text: 'OD', value: 13 },
  14: { text: 'BCBA', value: 14 },
  15: { text: 'RDN', value: 15 },
  16: { text: 'Acupuncturist', value: 16 },
  17: { text: 'RN', value: 17 },
  18: { text: 'Reiki', value: 18 },
  19: { text: 'Life Coach', value: 19 },
  20: { text: 'Hypnotherapist', value: 20 },
  21: { text: 'None', value: 21 },
  22: { text: 'Other', value: 22 }
}


export const StateTypes = {
  AL: { text: 'AL', value: 'AL' },
  AK: { text: 'AK', value: 'AK' },
  AZ: { text: 'AZ', value: 'AZ' },
  AR: { text: 'AR', value: 'AR' },
  CA: { text: 'CA', value: 'CA' },
  CO: { text: 'CO', value: 'CO' },
  CT: { text: 'CT', value: 'CT' },
  DE: { text: 'DE', value: 'DE' },
  FL: { text: 'FL', value: 'FL' },
  GA: { text: 'GA', value: 'GA' },
  HI: { text: 'HI', value: 'HI' },
  ID: { text: 'ID', value: 'ID' },
  IL: { text: 'IL', value: 'IL' },
  IN: { text: 'IN', value: 'IN' },
  IA: { text: 'IA', value: 'IA' },
  KS: { text: 'KS', value: 'KS' },
  KY: { text: 'KY', value: 'KY' },
  LA: { text: 'LA', value: 'LA' },
  ME: { text: 'ME', value: 'ME' },
  MD: { text: 'MD', value: 'MD' },
  MA: { text: 'MA', value: 'MA' },
  MI: { text: 'MI', value: 'MI' },
  MN: { text: 'MN', value: 'MN' },
  MS: { text: 'MS', value: 'MS' },
  MO: { text: 'MO', value: 'MO' },
  MT: { text: 'MT', value: 'MT' },
  NE: { text: 'NE', value: 'NE' },
  NV: { text: 'NV', value: 'NV' },
  NH: { text: 'NH', value: 'NH' },
  NJ: { text: 'NJ', value: 'NJ' },
  NM: { text: 'NM', value: 'NM' },
  NY: { text: 'NY', value: 'NY' },
  NC: { text: 'NC', value: 'NC' },
  ND: { text: 'ND', value: 'ND' },
  OH: { text: 'OH', value: 'OH' },
  OK: { text: 'OK', value: 'OK' },
  OR: { text: 'OR', value: 'OR' },
  PA: { text: 'PA', value: 'PA' },
  RI: { text: 'RI', value: 'RI' },
  SC: { text: 'SC', value: 'SC' },
  SD: { text: 'SD', value: 'SD' },
  TN: { text: 'TN', value: 'TN' },
  TX: { text: 'TX', value: 'TX' },
  UT: { text: 'UT', value: 'UT' },
  VT: { text: 'VT', value: 'VT' },
  VA: { text: 'VA', value: 'VA' },
  WA: { text: 'WA', value: 'WA' },
  WV: { text: 'WV', value: 'WV' },
  WI: { text: 'WI', value: 'WI' },
  WY: { text: 'WY', value: 'WY' }
}
